"""Make user

Revision ID: 31d2acf531b8
Revises: 
Create Date: 2017-07-18 19:21:28.799951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31d2acf531b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('splitwise_id', sa.Integer(), nullable=True),
        sa.Column('resource_owner_key', sa.String(length=40), nullable=True),
        sa.Column('resource_owner_secret', sa.String(length=40), nullable=True),
        sa.Column('last_update', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('resource_owner_key'),
        sa.UniqueConstraint('resource_owner_secret'),
        sa.UniqueConstraint('splitwise_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
