"""Add Expense table

Revision ID: 41e781d0952d
Revises: 31d2acf531b8
Create Date: 2017-07-18 19:33:30.638271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41e781d0952d'
down_revision = '31d2acf531b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('last_update', sa.DateTime(), nullable=True),
        sa.Column('original_currency', sa.Integer(), nullable=True),
        sa.Column('original_value', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expense')
    # ### end Alembic commands ###
